Start work on drawing
gnustep/libs-quartzcore pull request #5
Opened 2018-07-10 20:47 UTC by whiteShtef

2018-07-22 12:33 UTC, ivucica commented on CAAppKitBridge/Source/NSView+CAMethods.m
> +  NSLog(@"poy");
poy

2024-10-19 17:56 UTC, ethanc8 commented
@sbrki Do you still have the blog posts about the GSoC 2018 project that you did on this? Your blog seems to have gone down.

2025-04-01 12:06 UTC, ivucica requested changes
We should likely merge this with minimal changes applied. I've left these as suggestions if you have time to apply them (through web UI is fine). I'd squash these an merge them that way; despite losing the date in the commit history, I think that's nicer given the commit messages on the PR.

While not finished and somewhat messy, I *think* this is *closer* to having a working implementation than not merging it. To figure out more, I'd have to build the project and see how far we got all those years ago.

I might merge it as-is and then apply the cleanup, but it might be nicer if you did it.

2025-04-01 12:06 UTC, ivucica commented on CAAppKitBridge/Source/NSView+CAMethods.m
> +
```suggestion

  return; // Uncomment to write a capture of the layer drawn.
```

2025-04-01 12:06 UTC, ivucica commented on CAAppKitBridge/Source/NSView+CAMethods.m
> +  [data writeToFile:@"/tmp/ovojeruzno.png" atomically:YES];
```suggestion
  [data writeToFile:@"/tmp/drawLayerOutput.png" atomically:YES]; // TODO: Clean up and allow debug capture of layers to a uniquely-named file at an arbitrary-chosen path, controllable in a more standard way.
```

2025-04-01 12:06 UTC, ivucica commented on CAAppKitBridge/Source/NSView+CAMethods.m
>        return;
```suggestion
      // TODO: empty and remove the GSCAData unless a parent view also has wantsLayer set
      // (as implemented, wantsLayer only looks if the data has been set; therefore, setWantsLayer: won't affect its value)
      return;
```

2025-04-01 12:06 UTC, ivucica commented on CAAppKitBridge/Demo/DemoController.m
> +  NSLog(@"kmu");
```suggestion
  // ...
```

We can leave this as a semo of what can be overridden, but let's remove the message.

2025-04-04 17:43 UTC, ivucica commented
Pondering whether to squash the commits. I might squash them into fewer commits but with a date ending in 2018 and with Co-authored-by trailer or something like that.

2025-04-04 21:17 UTC, ethanc8 commented
I think squashing the commits with a date in 2018, with author sbirki and co-author as you would be good.

2025-06-11 01:07 UTC, merged